/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SocRouteImport } from './routes/soc'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWorkspacesRouteImport } from './routes/admin.workspaces'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AssistantSessionIdRouteImport } from './routes/assistant.$sessionId'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents.$incidentId'
import { Route as IncidentsEvidenceRouteImport } from './routes/incidents.evidence'
import { Route as IncidentsListRouteImport } from './routes/incidents.list'
import { Route as IncidentsPlaybooksRouteImport } from './routes/incidents.playbooks'
import { Route as IncidentsReportsRouteImport } from './routes/incidents.reports'
import { Route as IncidentsWorkspaceRouteImport } from './routes/incidents.workspace'
import { Route as IntelIndexRouteImport } from './routes/intel.index'
import { Route as IntelCveRouteImport } from './routes/intel.cve'
import { Route as IntelFeedRouteImport } from './routes/intel.feed'
import { Route as IntelIocsRouteImport } from './routes/intel.iocs'
import { Route as IntelLibraryRouteImport } from './routes/intel.library'
import { Route as IntelMalwareRouteImport } from './routes/intel.malware'
import { Route as IntelMapRouteImport } from './routes/intel.map'
import { Route as IntelMitreRouteImport } from './routes/intel.mitre'
import { Route as IntelReportsRouteImport } from './routes/intel.reports'
import { Route as IntelWatchlistsRouteImport } from './routes/intel.watchlists'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeTopicRouteImport } from './routes/knowledge.$topic'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as OpsAlertsRouteImport } from './routes/ops.alerts'
import { Route as OpsApiRouteImport } from './routes/ops.api'
import { Route as OpsBackupsRouteImport } from './routes/ops.backups'
import { Route as OpsDatabaseRouteImport } from './routes/ops.database'
import { Route as OpsDependenciesRouteImport } from './routes/ops.dependencies'
import { Route as OpsDeploymentsRouteImport } from './routes/ops.deployments'
import { Route as OpsDevsecopsRouteImport } from './routes/ops.devsecops'
import { Route as OpsDocsRouteImport } from './routes/ops.docs'
import { Route as OpsEnvironmentsRouteImport } from './routes/ops.environments'
import { Route as OpsLogsRouteImport } from './routes/ops.logs'
import { Route as OpsMetricsRouteImport } from './routes/ops.metrics'
import { Route as OpsSettingsRouteImport } from './routes/ops.settings'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsAnalyticsRouteImport } from './routes/reports.analytics'
import { Route as ReportsAuditRouteImport } from './routes/reports.audit'
import { Route as ReportsBoardRouteImport } from './routes/reports.board'
import { Route as ReportsBuilderRouteImport } from './routes/reports.builder'
import { Route as ReportsComplianceRouteImport } from './routes/reports.compliance'
import { Route as ReportsExportsRouteImport } from './routes/reports.exports'
import { Route as ReportsKnowledgeRouteImport } from './routes/reports.knowledge'
import { Route as ReportsLibraryRouteImport } from './routes/reports.library'
import { Route as ReportsRiskRouteImport } from './routes/reports.risk'
import { Route as ReportsComplianceIndexRouteImport } from './routes/reports.compliance.index'
import { Route as ReportsComplianceFrameworkRouteImport } from './routes/reports.compliance.$framework'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SocRoute = SocRouteImport.update({
  id: '/soc',
  path: '/soc',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AdminRoute,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantRoute,
} as any)
const AssistantSessionIdRoute = AssistantSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AssistantRoute,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsEvidenceRoute = IncidentsEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsListRoute = IncidentsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsPlaybooksRoute = IncidentsPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsReportsRoute = IncidentsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsWorkspaceRoute = IncidentsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => IncidentsRoute,
} as any)
const IntelIndexRoute = IntelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntelRoute,
} as any)
const IntelCveRoute = IntelCveRouteImport.update({
  id: '/cve',
  path: '/cve',
  getParentRoute: () => IntelRoute,
} as any)
const IntelFeedRoute = IntelFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => IntelRoute,
} as any)
const IntelIocsRoute = IntelIocsRouteImport.update({
  id: '/iocs',
  path: '/iocs',
  getParentRoute: () => IntelRoute,
} as any)
const IntelLibraryRoute = IntelLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => IntelRoute,
} as any)
const IntelMalwareRoute = IntelMalwareRouteImport.update({
  id: '/malware',
  path: '/malware',
  getParentRoute: () => IntelRoute,
} as any)
const IntelMapRoute = IntelMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => IntelRoute,
} as any)
const IntelMitreRoute = IntelMitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => IntelRoute,
} as any)
const IntelReportsRoute = IntelReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => IntelRoute,
} as any)
const IntelWatchlistsRoute = IntelWatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => IntelRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeTopicRoute = KnowledgeTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => KnowledgeRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAlertsRoute = OpsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => OpsRoute,
} as any)
const OpsApiRoute = OpsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => OpsRoute,
} as any)
const OpsBackupsRoute = OpsBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDatabaseRoute = OpsDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDependenciesRoute = OpsDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDeploymentsRoute = OpsDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDevsecopsRoute = OpsDevsecopsRouteImport.update({
  id: '/devsecops',
  path: '/devsecops',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDocsRoute = OpsDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => OpsRoute,
} as any)
const OpsEnvironmentsRoute = OpsEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => OpsRoute,
} as any)
const OpsLogsRoute = OpsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => OpsRoute,
} as any)
const OpsMetricsRoute = OpsMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSettingsRoute = OpsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OpsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsAnalyticsRoute = ReportsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsAuditRoute = ReportsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsBoardRoute = ReportsBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsBuilderRoute = ReportsBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsComplianceRoute = ReportsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsExportsRoute = ReportsExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsKnowledgeRoute = ReportsKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsLibraryRoute = ReportsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsRiskRoute = ReportsRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsComplianceIndexRoute = ReportsComplianceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsComplianceRoute,
} as any)
const ReportsComplianceFrameworkRoute =
  ReportsComplianceFrameworkRouteImport.update({
    id: '/$framework',
    path: '/$framework',
    getParentRoute: () => ReportsComplianceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/intel': typeof IntelRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/ops': typeof OpsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/soc': typeof SocRoute
  '/threats': typeof ThreatsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/assistant/$sessionId': typeof AssistantSessionIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/evidence': typeof IncidentsEvidenceRoute
  '/incidents/list': typeof IncidentsListRoute
  '/incidents/playbooks': typeof IncidentsPlaybooksRoute
  '/incidents/reports': typeof IncidentsReportsRoute
  '/incidents/workspace': typeof IncidentsWorkspaceRoute
  '/intel/cve': typeof IntelCveRoute
  '/intel/feed': typeof IntelFeedRoute
  '/intel/iocs': typeof IntelIocsRoute
  '/intel/library': typeof IntelLibraryRoute
  '/intel/malware': typeof IntelMalwareRoute
  '/intel/map': typeof IntelMapRoute
  '/intel/mitre': typeof IntelMitreRoute
  '/intel/reports': typeof IntelReportsRoute
  '/intel/watchlists': typeof IntelWatchlistsRoute
  '/knowledge/$topic': typeof KnowledgeTopicRoute
  '/ops/alerts': typeof OpsAlertsRoute
  '/ops/api': typeof OpsApiRoute
  '/ops/backups': typeof OpsBackupsRoute
  '/ops/database': typeof OpsDatabaseRoute
  '/ops/dependencies': typeof OpsDependenciesRoute
  '/ops/deployments': typeof OpsDeploymentsRoute
  '/ops/devsecops': typeof OpsDevsecopsRoute
  '/ops/docs': typeof OpsDocsRoute
  '/ops/environments': typeof OpsEnvironmentsRoute
  '/ops/logs': typeof OpsLogsRoute
  '/ops/metrics': typeof OpsMetricsRoute
  '/ops/settings': typeof OpsSettingsRoute
  '/reports/analytics': typeof ReportsAnalyticsRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/board': typeof ReportsBoardRoute
  '/reports/builder': typeof ReportsBuilderRoute
  '/reports/compliance': typeof ReportsComplianceRouteWithChildren
  '/reports/exports': typeof ReportsExportsRoute
  '/reports/knowledge': typeof ReportsKnowledgeRoute
  '/reports/library': typeof ReportsLibraryRoute
  '/reports/risk': typeof ReportsRiskRoute
  '/admin/': typeof AdminIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/intel/': typeof IntelIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/compliance/$framework': typeof ReportsComplianceFrameworkRoute
  '/reports/compliance/': typeof ReportsComplianceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/soc': typeof SocRoute
  '/threats': typeof ThreatsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/assistant/$sessionId': typeof AssistantSessionIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/evidence': typeof IncidentsEvidenceRoute
  '/incidents/list': typeof IncidentsListRoute
  '/incidents/playbooks': typeof IncidentsPlaybooksRoute
  '/incidents/reports': typeof IncidentsReportsRoute
  '/incidents/workspace': typeof IncidentsWorkspaceRoute
  '/intel/cve': typeof IntelCveRoute
  '/intel/feed': typeof IntelFeedRoute
  '/intel/iocs': typeof IntelIocsRoute
  '/intel/library': typeof IntelLibraryRoute
  '/intel/malware': typeof IntelMalwareRoute
  '/intel/map': typeof IntelMapRoute
  '/intel/mitre': typeof IntelMitreRoute
  '/intel/reports': typeof IntelReportsRoute
  '/intel/watchlists': typeof IntelWatchlistsRoute
  '/knowledge/$topic': typeof KnowledgeTopicRoute
  '/ops/alerts': typeof OpsAlertsRoute
  '/ops/api': typeof OpsApiRoute
  '/ops/backups': typeof OpsBackupsRoute
  '/ops/database': typeof OpsDatabaseRoute
  '/ops/dependencies': typeof OpsDependenciesRoute
  '/ops/deployments': typeof OpsDeploymentsRoute
  '/ops/devsecops': typeof OpsDevsecopsRoute
  '/ops/docs': typeof OpsDocsRoute
  '/ops/environments': typeof OpsEnvironmentsRoute
  '/ops/logs': typeof OpsLogsRoute
  '/ops/metrics': typeof OpsMetricsRoute
  '/ops/settings': typeof OpsSettingsRoute
  '/reports/analytics': typeof ReportsAnalyticsRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/board': typeof ReportsBoardRoute
  '/reports/builder': typeof ReportsBuilderRoute
  '/reports/exports': typeof ReportsExportsRoute
  '/reports/knowledge': typeof ReportsKnowledgeRoute
  '/reports/library': typeof ReportsLibraryRoute
  '/reports/risk': typeof ReportsRiskRoute
  '/admin': typeof AdminIndexRoute
  '/assistant': typeof AssistantIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/intel': typeof IntelIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/ops': typeof OpsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reports/compliance/$framework': typeof ReportsComplianceFrameworkRoute
  '/reports/compliance': typeof ReportsComplianceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/intel': typeof IntelRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/ops': typeof OpsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/soc': typeof SocRoute
  '/threats': typeof ThreatsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/assistant/$sessionId': typeof AssistantSessionIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/evidence': typeof IncidentsEvidenceRoute
  '/incidents/list': typeof IncidentsListRoute
  '/incidents/playbooks': typeof IncidentsPlaybooksRoute
  '/incidents/reports': typeof IncidentsReportsRoute
  '/incidents/workspace': typeof IncidentsWorkspaceRoute
  '/intel/cve': typeof IntelCveRoute
  '/intel/feed': typeof IntelFeedRoute
  '/intel/iocs': typeof IntelIocsRoute
  '/intel/library': typeof IntelLibraryRoute
  '/intel/malware': typeof IntelMalwareRoute
  '/intel/map': typeof IntelMapRoute
  '/intel/mitre': typeof IntelMitreRoute
  '/intel/reports': typeof IntelReportsRoute
  '/intel/watchlists': typeof IntelWatchlistsRoute
  '/knowledge/$topic': typeof KnowledgeTopicRoute
  '/ops/alerts': typeof OpsAlertsRoute
  '/ops/api': typeof OpsApiRoute
  '/ops/backups': typeof OpsBackupsRoute
  '/ops/database': typeof OpsDatabaseRoute
  '/ops/dependencies': typeof OpsDependenciesRoute
  '/ops/deployments': typeof OpsDeploymentsRoute
  '/ops/devsecops': typeof OpsDevsecopsRoute
  '/ops/docs': typeof OpsDocsRoute
  '/ops/environments': typeof OpsEnvironmentsRoute
  '/ops/logs': typeof OpsLogsRoute
  '/ops/metrics': typeof OpsMetricsRoute
  '/ops/settings': typeof OpsSettingsRoute
  '/reports/analytics': typeof ReportsAnalyticsRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/board': typeof ReportsBoardRoute
  '/reports/builder': typeof ReportsBuilderRoute
  '/reports/compliance': typeof ReportsComplianceRouteWithChildren
  '/reports/exports': typeof ReportsExportsRoute
  '/reports/knowledge': typeof ReportsKnowledgeRoute
  '/reports/library': typeof ReportsLibraryRoute
  '/reports/risk': typeof ReportsRiskRoute
  '/admin/': typeof AdminIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/intel/': typeof IntelIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/compliance/$framework': typeof ReportsComplianceFrameworkRoute
  '/reports/compliance/': typeof ReportsComplianceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analysis'
    | '/assistant'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/incidents'
    | '/intel'
    | '/knowledge'
    | '/login'
    | '/notifications'
    | '/ops'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/session-expired'
    | '/settings'
    | '/soc'
    | '/threats'
    | '/unauthorized'
    | '/upload'
    | '/verify-email'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/integrations'
    | '/admin/organizations'
    | '/admin/policies'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/admin/workspaces'
    | '/assistant/$sessionId'
    | '/incidents/$incidentId'
    | '/incidents/evidence'
    | '/incidents/list'
    | '/incidents/playbooks'
    | '/incidents/reports'
    | '/incidents/workspace'
    | '/intel/cve'
    | '/intel/feed'
    | '/intel/iocs'
    | '/intel/library'
    | '/intel/malware'
    | '/intel/map'
    | '/intel/mitre'
    | '/intel/reports'
    | '/intel/watchlists'
    | '/knowledge/$topic'
    | '/ops/alerts'
    | '/ops/api'
    | '/ops/backups'
    | '/ops/database'
    | '/ops/dependencies'
    | '/ops/deployments'
    | '/ops/devsecops'
    | '/ops/docs'
    | '/ops/environments'
    | '/ops/logs'
    | '/ops/metrics'
    | '/ops/settings'
    | '/reports/analytics'
    | '/reports/audit'
    | '/reports/board'
    | '/reports/builder'
    | '/reports/compliance'
    | '/reports/exports'
    | '/reports/knowledge'
    | '/reports/library'
    | '/reports/risk'
    | '/admin/'
    | '/assistant/'
    | '/incidents/'
    | '/intel/'
    | '/knowledge/'
    | '/ops/'
    | '/reports/'
    | '/reports/compliance/$framework'
    | '/reports/compliance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/settings'
    | '/soc'
    | '/threats'
    | '/unauthorized'
    | '/upload'
    | '/verify-email'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/integrations'
    | '/admin/organizations'
    | '/admin/policies'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/admin/workspaces'
    | '/assistant/$sessionId'
    | '/incidents/$incidentId'
    | '/incidents/evidence'
    | '/incidents/list'
    | '/incidents/playbooks'
    | '/incidents/reports'
    | '/incidents/workspace'
    | '/intel/cve'
    | '/intel/feed'
    | '/intel/iocs'
    | '/intel/library'
    | '/intel/malware'
    | '/intel/map'
    | '/intel/mitre'
    | '/intel/reports'
    | '/intel/watchlists'
    | '/knowledge/$topic'
    | '/ops/alerts'
    | '/ops/api'
    | '/ops/backups'
    | '/ops/database'
    | '/ops/dependencies'
    | '/ops/deployments'
    | '/ops/devsecops'
    | '/ops/docs'
    | '/ops/environments'
    | '/ops/logs'
    | '/ops/metrics'
    | '/ops/settings'
    | '/reports/analytics'
    | '/reports/audit'
    | '/reports/board'
    | '/reports/builder'
    | '/reports/exports'
    | '/reports/knowledge'
    | '/reports/library'
    | '/reports/risk'
    | '/admin'
    | '/assistant'
    | '/incidents'
    | '/intel'
    | '/knowledge'
    | '/ops'
    | '/reports'
    | '/reports/compliance/$framework'
    | '/reports/compliance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analysis'
    | '/assistant'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/incidents'
    | '/intel'
    | '/knowledge'
    | '/login'
    | '/notifications'
    | '/ops'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/session-expired'
    | '/settings'
    | '/soc'
    | '/threats'
    | '/unauthorized'
    | '/upload'
    | '/verify-email'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/integrations'
    | '/admin/organizations'
    | '/admin/policies'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/admin/workspaces'
    | '/assistant/$sessionId'
    | '/incidents/$incidentId'
    | '/incidents/evidence'
    | '/incidents/list'
    | '/incidents/playbooks'
    | '/incidents/reports'
    | '/incidents/workspace'
    | '/intel/cve'
    | '/intel/feed'
    | '/intel/iocs'
    | '/intel/library'
    | '/intel/malware'
    | '/intel/map'
    | '/intel/mitre'
    | '/intel/reports'
    | '/intel/watchlists'
    | '/knowledge/$topic'
    | '/ops/alerts'
    | '/ops/api'
    | '/ops/backups'
    | '/ops/database'
    | '/ops/dependencies'
    | '/ops/deployments'
    | '/ops/devsecops'
    | '/ops/docs'
    | '/ops/environments'
    | '/ops/logs'
    | '/ops/metrics'
    | '/ops/settings'
    | '/reports/analytics'
    | '/reports/audit'
    | '/reports/board'
    | '/reports/builder'
    | '/reports/compliance'
    | '/reports/exports'
    | '/reports/knowledge'
    | '/reports/library'
    | '/reports/risk'
    | '/admin/'
    | '/assistant/'
    | '/incidents/'
    | '/intel/'
    | '/knowledge/'
    | '/ops/'
    | '/reports/'
    | '/reports/compliance/$framework'
    | '/reports/compliance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  AssistantRoute: typeof AssistantRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  IncidentsRoute: typeof IncidentsRouteWithChildren
  IntelRoute: typeof IntelRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OpsRoute: typeof OpsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SettingsRoute: typeof SettingsRoute
  SocRoute: typeof SocRoute
  ThreatsRoute: typeof ThreatsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UploadRoute: typeof UploadRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soc': {
      id: '/soc'
      path: '/soc'
      fullPath: '/soc'
      preLoaderRoute: typeof SocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/assistant/$sessionId': {
      id: '/assistant/$sessionId'
      path: '/$sessionId'
      fullPath: '/assistant/$sessionId'
      preLoaderRoute: typeof AssistantSessionIdRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/evidence': {
      id: '/incidents/evidence'
      path: '/evidence'
      fullPath: '/incidents/evidence'
      preLoaderRoute: typeof IncidentsEvidenceRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/list': {
      id: '/incidents/list'
      path: '/list'
      fullPath: '/incidents/list'
      preLoaderRoute: typeof IncidentsListRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/playbooks': {
      id: '/incidents/playbooks'
      path: '/playbooks'
      fullPath: '/incidents/playbooks'
      preLoaderRoute: typeof IncidentsPlaybooksRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/reports': {
      id: '/incidents/reports'
      path: '/reports'
      fullPath: '/incidents/reports'
      preLoaderRoute: typeof IncidentsReportsRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/workspace': {
      id: '/incidents/workspace'
      path: '/workspace'
      fullPath: '/incidents/workspace'
      preLoaderRoute: typeof IncidentsWorkspaceRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/intel/': {
      id: '/intel/'
      path: '/'
      fullPath: '/intel/'
      preLoaderRoute: typeof IntelIndexRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/cve': {
      id: '/intel/cve'
      path: '/cve'
      fullPath: '/intel/cve'
      preLoaderRoute: typeof IntelCveRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/feed': {
      id: '/intel/feed'
      path: '/feed'
      fullPath: '/intel/feed'
      preLoaderRoute: typeof IntelFeedRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/iocs': {
      id: '/intel/iocs'
      path: '/iocs'
      fullPath: '/intel/iocs'
      preLoaderRoute: typeof IntelIocsRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/library': {
      id: '/intel/library'
      path: '/library'
      fullPath: '/intel/library'
      preLoaderRoute: typeof IntelLibraryRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/malware': {
      id: '/intel/malware'
      path: '/malware'
      fullPath: '/intel/malware'
      preLoaderRoute: typeof IntelMalwareRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/map': {
      id: '/intel/map'
      path: '/map'
      fullPath: '/intel/map'
      preLoaderRoute: typeof IntelMapRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/mitre': {
      id: '/intel/mitre'
      path: '/mitre'
      fullPath: '/intel/mitre'
      preLoaderRoute: typeof IntelMitreRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/reports': {
      id: '/intel/reports'
      path: '/reports'
      fullPath: '/intel/reports'
      preLoaderRoute: typeof IntelReportsRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/watchlists': {
      id: '/intel/watchlists'
      path: '/watchlists'
      fullPath: '/intel/watchlists'
      preLoaderRoute: typeof IntelWatchlistsRouteImport
      parentRoute: typeof IntelRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$topic': {
      id: '/knowledge/$topic'
      path: '/$topic'
      fullPath: '/knowledge/$topic'
      preLoaderRoute: typeof KnowledgeTopicRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/alerts': {
      id: '/ops/alerts'
      path: '/alerts'
      fullPath: '/ops/alerts'
      preLoaderRoute: typeof OpsAlertsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/api': {
      id: '/ops/api'
      path: '/api'
      fullPath: '/ops/api'
      preLoaderRoute: typeof OpsApiRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/backups': {
      id: '/ops/backups'
      path: '/backups'
      fullPath: '/ops/backups'
      preLoaderRoute: typeof OpsBackupsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/database': {
      id: '/ops/database'
      path: '/database'
      fullPath: '/ops/database'
      preLoaderRoute: typeof OpsDatabaseRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/dependencies': {
      id: '/ops/dependencies'
      path: '/dependencies'
      fullPath: '/ops/dependencies'
      preLoaderRoute: typeof OpsDependenciesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/deployments': {
      id: '/ops/deployments'
      path: '/deployments'
      fullPath: '/ops/deployments'
      preLoaderRoute: typeof OpsDeploymentsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/devsecops': {
      id: '/ops/devsecops'
      path: '/devsecops'
      fullPath: '/ops/devsecops'
      preLoaderRoute: typeof OpsDevsecopsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/docs': {
      id: '/ops/docs'
      path: '/docs'
      fullPath: '/ops/docs'
      preLoaderRoute: typeof OpsDocsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/environments': {
      id: '/ops/environments'
      path: '/environments'
      fullPath: '/ops/environments'
      preLoaderRoute: typeof OpsEnvironmentsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/logs': {
      id: '/ops/logs'
      path: '/logs'
      fullPath: '/ops/logs'
      preLoaderRoute: typeof OpsLogsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/metrics': {
      id: '/ops/metrics'
      path: '/metrics'
      fullPath: '/ops/metrics'
      preLoaderRoute: typeof OpsMetricsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/settings': {
      id: '/ops/settings'
      path: '/settings'
      fullPath: '/ops/settings'
      preLoaderRoute: typeof OpsSettingsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/analytics': {
      id: '/reports/analytics'
      path: '/analytics'
      fullPath: '/reports/analytics'
      preLoaderRoute: typeof ReportsAnalyticsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/audit': {
      id: '/reports/audit'
      path: '/audit'
      fullPath: '/reports/audit'
      preLoaderRoute: typeof ReportsAuditRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/board': {
      id: '/reports/board'
      path: '/board'
      fullPath: '/reports/board'
      preLoaderRoute: typeof ReportsBoardRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/builder': {
      id: '/reports/builder'
      path: '/builder'
      fullPath: '/reports/builder'
      preLoaderRoute: typeof ReportsBuilderRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/compliance': {
      id: '/reports/compliance'
      path: '/compliance'
      fullPath: '/reports/compliance'
      preLoaderRoute: typeof ReportsComplianceRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/exports': {
      id: '/reports/exports'
      path: '/exports'
      fullPath: '/reports/exports'
      preLoaderRoute: typeof ReportsExportsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/knowledge': {
      id: '/reports/knowledge'
      path: '/knowledge'
      fullPath: '/reports/knowledge'
      preLoaderRoute: typeof ReportsKnowledgeRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/library': {
      id: '/reports/library'
      path: '/library'
      fullPath: '/reports/library'
      preLoaderRoute: typeof ReportsLibraryRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/risk': {
      id: '/reports/risk'
      path: '/risk'
      fullPath: '/reports/risk'
      preLoaderRoute: typeof ReportsRiskRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/compliance/': {
      id: '/reports/compliance/'
      path: '/'
      fullPath: '/reports/compliance/'
      preLoaderRoute: typeof ReportsComplianceIndexRouteImport
      parentRoute: typeof ReportsComplianceRoute
    }
    '/reports/compliance/$framework': {
      id: '/reports/compliance/$framework'
      path: '/$framework'
      fullPath: '/reports/compliance/$framework'
      preLoaderRoute: typeof ReportsComplianceFrameworkRouteImport
      parentRoute: typeof ReportsComplianceRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AssistantRouteChildren {
  AssistantSessionIdRoute: typeof AssistantSessionIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantSessionIdRoute: AssistantSessionIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

interface IncidentsRouteChildren {
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  IncidentsEvidenceRoute: typeof IncidentsEvidenceRoute
  IncidentsListRoute: typeof IncidentsListRoute
  IncidentsPlaybooksRoute: typeof IncidentsPlaybooksRoute
  IncidentsReportsRoute: typeof IncidentsReportsRoute
  IncidentsWorkspaceRoute: typeof IncidentsWorkspaceRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  IncidentsEvidenceRoute: IncidentsEvidenceRoute,
  IncidentsListRoute: IncidentsListRoute,
  IncidentsPlaybooksRoute: IncidentsPlaybooksRoute,
  IncidentsReportsRoute: IncidentsReportsRoute,
  IncidentsWorkspaceRoute: IncidentsWorkspaceRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

interface IntelRouteChildren {
  IntelCveRoute: typeof IntelCveRoute
  IntelFeedRoute: typeof IntelFeedRoute
  IntelIocsRoute: typeof IntelIocsRoute
  IntelLibraryRoute: typeof IntelLibraryRoute
  IntelMalwareRoute: typeof IntelMalwareRoute
  IntelMapRoute: typeof IntelMapRoute
  IntelMitreRoute: typeof IntelMitreRoute
  IntelReportsRoute: typeof IntelReportsRoute
  IntelWatchlistsRoute: typeof IntelWatchlistsRoute
  IntelIndexRoute: typeof IntelIndexRoute
}

const IntelRouteChildren: IntelRouteChildren = {
  IntelCveRoute: IntelCveRoute,
  IntelFeedRoute: IntelFeedRoute,
  IntelIocsRoute: IntelIocsRoute,
  IntelLibraryRoute: IntelLibraryRoute,
  IntelMalwareRoute: IntelMalwareRoute,
  IntelMapRoute: IntelMapRoute,
  IntelMitreRoute: IntelMitreRoute,
  IntelReportsRoute: IntelReportsRoute,
  IntelWatchlistsRoute: IntelWatchlistsRoute,
  IntelIndexRoute: IntelIndexRoute,
}

const IntelRouteWithChildren = IntelRoute._addFileChildren(IntelRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeTopicRoute: typeof KnowledgeTopicRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeTopicRoute: KnowledgeTopicRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface OpsRouteChildren {
  OpsAlertsRoute: typeof OpsAlertsRoute
  OpsApiRoute: typeof OpsApiRoute
  OpsBackupsRoute: typeof OpsBackupsRoute
  OpsDatabaseRoute: typeof OpsDatabaseRoute
  OpsDependenciesRoute: typeof OpsDependenciesRoute
  OpsDeploymentsRoute: typeof OpsDeploymentsRoute
  OpsDevsecopsRoute: typeof OpsDevsecopsRoute
  OpsDocsRoute: typeof OpsDocsRoute
  OpsEnvironmentsRoute: typeof OpsEnvironmentsRoute
  OpsLogsRoute: typeof OpsLogsRoute
  OpsMetricsRoute: typeof OpsMetricsRoute
  OpsSettingsRoute: typeof OpsSettingsRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAlertsRoute: OpsAlertsRoute,
  OpsApiRoute: OpsApiRoute,
  OpsBackupsRoute: OpsBackupsRoute,
  OpsDatabaseRoute: OpsDatabaseRoute,
  OpsDependenciesRoute: OpsDependenciesRoute,
  OpsDeploymentsRoute: OpsDeploymentsRoute,
  OpsDevsecopsRoute: OpsDevsecopsRoute,
  OpsDocsRoute: OpsDocsRoute,
  OpsEnvironmentsRoute: OpsEnvironmentsRoute,
  OpsLogsRoute: OpsLogsRoute,
  OpsMetricsRoute: OpsMetricsRoute,
  OpsSettingsRoute: OpsSettingsRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface ReportsComplianceRouteChildren {
  ReportsComplianceFrameworkRoute: typeof ReportsComplianceFrameworkRoute
  ReportsComplianceIndexRoute: typeof ReportsComplianceIndexRoute
}

const ReportsComplianceRouteChildren: ReportsComplianceRouteChildren = {
  ReportsComplianceFrameworkRoute: ReportsComplianceFrameworkRoute,
  ReportsComplianceIndexRoute: ReportsComplianceIndexRoute,
}

const ReportsComplianceRouteWithChildren =
  ReportsComplianceRoute._addFileChildren(ReportsComplianceRouteChildren)

interface ReportsRouteChildren {
  ReportsAnalyticsRoute: typeof ReportsAnalyticsRoute
  ReportsAuditRoute: typeof ReportsAuditRoute
  ReportsBoardRoute: typeof ReportsBoardRoute
  ReportsBuilderRoute: typeof ReportsBuilderRoute
  ReportsComplianceRoute: typeof ReportsComplianceRouteWithChildren
  ReportsExportsRoute: typeof ReportsExportsRoute
  ReportsKnowledgeRoute: typeof ReportsKnowledgeRoute
  ReportsLibraryRoute: typeof ReportsLibraryRoute
  ReportsRiskRoute: typeof ReportsRiskRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsAnalyticsRoute: ReportsAnalyticsRoute,
  ReportsAuditRoute: ReportsAuditRoute,
  ReportsBoardRoute: ReportsBoardRoute,
  ReportsBuilderRoute: ReportsBuilderRoute,
  ReportsComplianceRoute: ReportsComplianceRouteWithChildren,
  ReportsExportsRoute: ReportsExportsRoute,
  ReportsKnowledgeRoute: ReportsKnowledgeRoute,
  ReportsLibraryRoute: ReportsLibraryRoute,
  ReportsRiskRoute: ReportsRiskRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  AssistantRoute: AssistantRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  IncidentsRoute: IncidentsRouteWithChildren,
  IntelRoute: IntelRouteWithChildren,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OpsRoute: OpsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SettingsRoute: SettingsRoute,
  SocRoute: SocRoute,
  ThreatsRoute: ThreatsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UploadRoute: UploadRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
