package com.ankit.deeppacketinspection.api.service;

import com.ankit.deeppacketinspection.analysis.Statistics;
import com.ankit.deeppacketinspection.analysis.ThreatDetector;
import com.ankit.deeppacketinspection.model.AnalysisResult;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.IOException;

@Service
public class PdfReportService {

    private final AnalysisStateService stateService;

    public PdfReportService(
            AnalysisStateService stateService) {

        this.stateService = stateService;

    }

    public File generatePdf() throws IOException {

        AnalysisResult result =
                stateService.getLatestAnalysis();

        if (result == null) {

            throw new IOException(
                    "No analysis available."
            );

        }

        Statistics statistics =
                result.getStatistics();

        ThreatDetector detector =
                result.getThreatDetector();

        File outputDirectory =
                new File("output");

        if (!outputDirectory.exists()) {

            outputDirectory.mkdirs();

        }

        File pdfFile =
                new File(outputDirectory,
                        "traffic_report.pdf");

        PDDocument document =
                new PDDocument();

        PDPage page =
                new PDPage();

        document.addPage(page);

        PDPageContentStream content =
                new PDPageContentStream(
                        document,
                        page
                );

        PDType1Font font =
                new PDType1Font(
                        Standard14Fonts.FontName.HELVETICA
                );

        content.beginText();

        content.setFont(font, 18);

        content.setLeading(22);

        content.newLineAtOffset(50, 750);

        content.showText("AI Powered Deep Packet Inspection");

        content.newLine();

        content.newLine();

        content.setFont(font, 14);

        content.showText("Analysis Report");

        content.newLine();
        content.newLine();

        content.showText("Total Packets : "
                + statistics.getTotalPackets());

        content.newLine();

        content.showText("Total Flows : "
                + statistics.getTotalFlows());

        content.newLine();

        content.showText("Threat Alerts : "
                + detector.getTotalAlerts());

        content.newLine();

        content.showText("IPv4 Packets : "
                + statistics.getIpv4Packets());

        content.newLine();

        content.showText("IPv6 Packets : "
                + statistics.getIpv6Packets());

        content.newLine();

        content.showText("TCP Packets : "
                + statistics.getTcpPackets());

        content.newLine();

        content.showText("UDP Packets : "
                + statistics.getUdpPackets());

        content.newLine();

        content.showText("HTTP Packets : "
                + statistics.getHttpPackets());

        content.newLine();

        content.showText("HTTPS Packets : "
                + statistics.getHttpsPackets());

        content.newLine();

        content.showText("DNS Packets : "
                + statistics.getDnsPackets());

        content.newLine();
        content.newLine();

        content.showText("Generated by AI Powered DPI");

        content.endText();

        content.close();

        document.save(pdfFile);

        document.close();

        return pdfFile;

    }

}